baseURL = "https://ktran03.github.io/"
languageCode = "en-us"
title = "Bai Yue History"
theme = "ananke"

[params]
  author = "ktran03"
  description = "Uncovering the lost history of the Bai Yue people."

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Articles"
    url = "/posts/"
    weight = 3
